USE PORTFOLIO_GESTAO
GO

IF OBJECT_ID('USUARIO', 'U') IS NULL
BEGIN
    CREATE TABLE USUARIO
    (
        ID_USUARIO      INT IDENTITY(1,1) NOT NULL,
        NOME            VARCHAR(100) NOT NULL,
        LOGIN           VARCHAR(50) NOT NULL,
        SENHA_HASH      VARCHAR(255) NOT NULL,
        ATIVO           BIT NOT NULL DEFAULT 1,
        DTH_CADASTRO    DATETIME2 NOT NULL DEFAULT GETDATE(),

        CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
        CONSTRAINT UQ_USUARIO_LOGIN UNIQUE (LOGIN)
    )
END
GO