USE PORTFOLIO_GESTAO
GO

IF OBJECT_ID('CLIENTE', 'U') IS NULL
BEGIN
    CREATE TABLE CLIENTE
    (
        ID_CLIENTE      INT IDENTITY(1,1) NOT NULL,
        NOME            VARCHAR(120) NOT NULL,
        DOCUMENTO       VARCHAR(20) NULL,
        EMAIL           VARCHAR(150) NULL,
        TELEFONE        VARCHAR(20) NULL,
        ATIVO           BIT NOT NULL DEFAULT 1,
        DTH_CADASTRO    DATETIME2 NOT NULL DEFAULT GETDATE(),

        CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
    )
END
GO
